#!/bin/bash
# Boot FitPub + PostgreSQL/PostGIS + MailPit + gate-proxy for OpenHost.
#
# Topology:
#
#   browser / fediverse peer
#     → OpenHost outer proxy (TLS termination)
#     → OpenHost router (subdomain fitpub.<zone>; stamps
#                        X-OpenHost-Is-Owner on owner requests)
#     → container :8080   (auth_proxy.py — hybrid gate)
#     ├→ 127.0.0.1:8081   FitPub (Spring Boot, prod profile)
#     ├→ 127.0.0.1:8025   MailPit web UI (served under /mailpit)
#     └  127.0.0.1:5432   PostgreSQL+PostGIS  ← FitPub
#        127.0.0.1:1025   MailPit SMTP        ← FitPub verification mail
#
# First boot:
#   * generates FitPub's required secrets (DB password, JWT secret,
#     email secret, actuator password) into $PERSIST/secrets.env
#   * initdb's PostgreSQL into $PERSIST/postgres and creates the
#     fitpub role/database with the PostGIS extension
#
# Every boot:
#   * sources $PERSIST/config.env (if present) so the operator can
#     override any FITPUB_* variable — external SMTP, admin emails,
#     registration password, feature flags — without rebuilding
#   * derives FITPUB_DOMAIN / FITPUB_BASE_URL from the OpenHost env
#
# bash (not /bin/sh) for `wait -n` and `[[ ... ]]`.

set -euo pipefail

log() { echo "[start.sh] $*"; }

PERSIST="${OPENHOST_APP_DATA_DIR:-/data/app_data/fitpub}"
TEMP="${OPENHOST_APP_TEMP_DIR:-/tmp}"

PGDATA="$PERSIST/postgres"
UPLOADS_DIR="$PERSIST/uploads"
IMAGES_DIR="$PERSIST/images"
LOGS_DIR="$PERSIST/logs"
MAILPIT_DIR="$PERSIST/mailpit"
TILES_DIR="$TEMP/tiles"
SECRETS_FILE="$PERSIST/secrets.env"
CONFIG_FILE="$PERSIST/config.env"

mkdir -p "$UPLOADS_DIR" "$IMAGES_DIR" "$LOGS_DIR" "$MAILPIT_DIR" "$TILES_DIR"

# Prod config hardcodes the log file to /app/logs/application.log;
# point that at persistent storage.
rm -rf /app/logs
ln -s "$LOGS_DIR" /app/logs

# uid 1001 = fitpub, per the upstream image. Rootless podman remaps
# uids outside the container, but inside it's still 1001, which is
# what the JVM and MailPit care about.
chown -R 1001:1001 "$UPLOADS_DIR" "$IMAGES_DIR" "$LOGS_DIR" "$MAILPIT_DIR" "$TILES_DIR" 2>/dev/null || true

# -----------------------------------------------------------------
# Secrets: generate once, persist forever
# -----------------------------------------------------------------

rand() { head -c 48 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c "${1:-43}"; }

if [[ ! -f "$SECRETS_FILE" ]]; then
    log "First boot: generating FitPub secrets"
    umask 077
    cat > "$SECRETS_FILE" <<EOF
# Auto-generated by start.sh on first boot. Deleting individual lines
# regenerates them on next start — but note that rotating
# FITPUB_DATABASE_PASSWORD requires a matching ALTER ROLE in postgres,
# and rotating FITPUB_JWT_SECRET logs every browser out.
FITPUB_DATABASE_PASSWORD='$(rand 32)'
FITPUB_JWT_SECRET='$(rand 64)'
FITPUB_EMAIL_SECRET='$(rand 64)'
FITPUB_ACTUATOR_PASSWORD='$(rand 32)'
EOF
    umask 022
fi

# shellcheck disable=SC1090
source "$SECRETS_FILE"

# -----------------------------------------------------------------
# Derived defaults (overridable via config.env below)
# -----------------------------------------------------------------

FITPUB_DOMAIN="${OPENHOST_APP_NAME:-fitpub}.${OPENHOST_ZONE_DOMAIN:-localhost}"
FITPUB_BASE_URL="https://$FITPUB_DOMAIN"
FITPUB_MAIL_FROM_ADDRESS="fitpub@$FITPUB_DOMAIN"
FITPUB_MAIL_FROM_NAME="FitPub"
# All mail lands in the bundled MailPit regardless of address, so the
# owner registering with this address gets the bootstrap admin role.
FITPUB_ADMIN_EMAILS="admin@$FITPUB_DOMAIN"
FITPUB_ACTUATOR_USERNAME="actuator"
# Backfill missing remote-activity details on startup. Cheap on a
# personal instance and repairs gaps after federation outages.
FITPUB_REMOTE_ACTIVITY_BACKFILL="${FITPUB_REMOTE_ACTIVITY_BACKFILL:-true}"

# Operator overrides — external SMTP, extra admin emails, invite
# password, feature flags... Anything exported here beats the
# defaults above and is passed through to FitPub.
if [[ -f "$CONFIG_FILE" ]]; then
    log "Sourcing operator overrides from $CONFIG_FILE"
    set -a
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    set +a
fi

export FITPUB_DOMAIN FITPUB_BASE_URL FITPUB_MAIL_FROM_ADDRESS \
       FITPUB_MAIL_FROM_NAME FITPUB_ADMIN_EMAILS FITPUB_ACTUATOR_USERNAME \
       FITPUB_DATABASE_PASSWORD FITPUB_JWT_SECRET FITPUB_EMAIL_SECRET \
       FITPUB_ACTUATOR_PASSWORD FITPUB_REMOTE_ACTIVITY_BACKFILL
ADMIN_EMAILS_DEFAULT="admin@$FITPUB_DOMAIN"

# -----------------------------------------------------------------
# PostgreSQL + PostGIS
# -----------------------------------------------------------------

# Alpine puts the server binaries in /usr/libexec/postgresqlNN (with
# /usr/bin symlinks), Debian/Ubuntu in /usr/lib/postgresql/NN/bin.
PG_BIN="$( (ls -d /usr/libexec/postgresql*/ /usr/lib/postgresql/*/bin/ 2>/dev/null || true) | sort -V | tail -1 )"
PG_BIN="${PG_BIN%/}"
if [[ -z "$PG_BIN" || ! -x "$PG_BIN/initdb" ]]; then
    PG_BIN="$(dirname "$(command -v initdb)")"
fi
log "Using PostgreSQL binaries from $PG_BIN"

# /run is a tmpfs under podman; recreate the socket dir every boot.
mkdir -p /var/run/postgresql
chown postgres:postgres /var/run/postgresql

# Privilege-drop helper: su-exec (Alpine base) or setpriv (util-linux,
# Ubuntu base). su-exec first — BusyBox ships a limited setpriv
# without --reuid that would otherwise win the lookup.
if command -v su-exec >/dev/null; then
    run_as() { local u="$1"; shift; su-exec "$u" "$@"; }
else
    run_as() { local u="$1"; shift; setpriv --reuid="$u" --regid="$u" --clear-groups "$@"; }
fi
as_postgres() { run_as postgres "$@"; }

if [[ ! -f "$PGDATA/PG_VERSION" ]]; then
    log "First boot: initializing PostgreSQL cluster in $PGDATA"
    mkdir -p "$PGDATA"
    chown postgres:postgres "$PGDATA"
    chmod 700 "$PGDATA"
    as_postgres "$PG_BIN/initdb" -D "$PGDATA" \
        --locale=C.UTF-8 \
        --auth-local=trust \
        --auth-host=scram-sha-256
fi

log "Starting PostgreSQL"
as_postgres "$PG_BIN/postgres" -D "$PGDATA" \
    -c listen_addresses=127.0.0.1 \
    -c shared_buffers=128MB \
    -c unix_socket_directories=/var/run/postgresql &
PG_PID=$!

for _ in $(seq 1 60); do
    if as_postgres "$PG_BIN/pg_isready" -q -h /var/run/postgresql; then
        break
    fi
    if ! kill -0 "$PG_PID" 2>/dev/null; then
        log "PostgreSQL exited during startup"
        exit 1
    fi
    sleep 1
done
log "PostgreSQL is ready"

# Idempotent role/db/extension setup. Local (socket) connections are
# `trust` for the postgres superuser only reachable from inside the
# container; FitPub connects over 127.0.0.1 with scram auth.
as_postgres "$PG_BIN/psql" -v ON_ERROR_STOP=1 -q <<EOF
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'fitpub') THEN
        CREATE ROLE fitpub LOGIN;
    END IF;
END
\$\$;
ALTER ROLE fitpub PASSWORD '$FITPUB_DATABASE_PASSWORD';
SELECT 'CREATE DATABASE fitpub OWNER fitpub'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'fitpub') \gexec
EOF
as_postgres "$PG_BIN/psql" -v ON_ERROR_STOP=1 -q -d fitpub \
    -c "CREATE EXTENSION IF NOT EXISTS postgis;"

# Single-owner admin bootstrap: FitPub grants the admin role to
# accounts whose email is listed in FITPUB_ADMIN_EMAILS. The zone
# owner may already have registered with an arbitrary address, so if
# the operator hasn't configured the list and exactly one user
# exists, treat that user as the instance owner and add their email.
if [[ "$FITPUB_ADMIN_EMAILS" == "$ADMIN_EMAILS_DEFAULT" ]]; then
    # to_regclass guard: on the very first boot Flyway hasn't created
    # the schema yet, so the users table only exists from the second
    # boot on (i.e. after "Update and reload" or a restart).
    SOLE_EMAIL=""
    if [[ "$(as_postgres "$PG_BIN/psql" -d fitpub -tA \
            -c "SELECT to_regclass('public.users') IS NOT NULL")" == "t" ]]; then
        SOLE_EMAIL="$(as_postgres "$PG_BIN/psql" -d fitpub -tA \
            -c "SELECT email FROM users" 2>/dev/null || true)"
    fi
    if [[ -n "$SOLE_EMAIL" && "$(wc -l <<< "$SOLE_EMAIL")" -eq 1 ]]; then
        log "Sole registered user detected; granting admin to $SOLE_EMAIL"
        export FITPUB_ADMIN_EMAILS="$ADMIN_EMAILS_DEFAULT,$SOLE_EMAIL"
    fi
fi

# -----------------------------------------------------------------
# MailPit — local SMTP sink; UI served under /mailpit via the proxy
# -----------------------------------------------------------------

log "Starting MailPit (SMTP 127.0.0.1:1025, UI 127.0.0.1:8025)"
run_as fitpub env HOME=/tmp \
    /usr/local/bin/mailpit \
    --smtp 127.0.0.1:1025 \
    --listen 127.0.0.1:8025 \
    --webroot /mailpit \
    --database "$MAILPIT_DIR/mailpit.db" &
MAILPIT_PID=$!

# -----------------------------------------------------------------
# FitPub
# -----------------------------------------------------------------

log "Starting FitPub on 127.0.0.1:8081 (base URL $FITPUB_BASE_URL)"
run_as fitpub env \
    HOME=/tmp \
    SPRING_PROFILES_ACTIVE=prod \
    SERVER_ADDRESS=127.0.0.1 \
    FITPUB_PORT=8081 \
    FITPUB_DATABASE_URL="jdbc:postgresql://127.0.0.1:5432/fitpub" \
    FITPUB_DATABASE_USERNAME=fitpub \
    FITPUB_MAIL_HOST="${FITPUB_MAIL_HOST:-127.0.0.1}" \
    FITPUB_MAIL_PORT="${FITPUB_MAIL_PORT:-1025}" \
    FITPUB_FILE_UPLOAD_DIR="$UPLOADS_DIR" \
    FITPUB_IMAGES_PATH="$IMAGES_DIR" \
    FITPUB_TILE_CACHE_PATH="$TILES_DIR" \
    FITPUB_PAGES_PATH=/app/pages \
    java \
        -XX:+UseContainerSupport \
        -XX:MaxRAMPercentage=50.0 \
        -Djava.security.egd=file:/dev/./urandom \
        -jar /app/fitpub.jar &
FITPUB_PID=$!

# -----------------------------------------------------------------
# Gate-proxy — the only listener OpenHost routes to
# -----------------------------------------------------------------

log "Starting gate-proxy on 0.0.0.0:8080"
AUTH_PROXY_LISTEN_PORT="${AUTH_PROXY_LISTEN_PORT:-8080}" \
FITPUB_UPSTREAM=127.0.0.1:8081 \
MAILPIT_UPSTREAM=127.0.0.1:8025 \
ACTUATOR_USERNAME="$FITPUB_ACTUATOR_USERNAME" \
ACTUATOR_PASSWORD="$FITPUB_ACTUATOR_PASSWORD" \
FORWARDED_HOST="$FITPUB_DOMAIN" \
FORWARDED_PROTO="${FORWARDED_PROTO:-https}" \
    python3 /opt/openhost-fitpub/auth_proxy.py &
PROXY_PID=$!

# -----------------------------------------------------------------
# Supervision — first child to exit takes the container down
# -----------------------------------------------------------------

ALL_PIDS=("$PG_PID" "$MAILPIT_PID" "$FITPUB_PID" "$PROXY_PID")
trap 'kill -TERM "${ALL_PIDS[@]}" 2>/dev/null; wait' TERM INT

set +e
wait -n "${ALL_PIDS[@]}"
EXIT_CODE=$?
set -e

log "A child exited (code=$EXIT_CODE); shutting down"
# Stop FitPub before PostgreSQL so in-flight transactions close cleanly.
kill -TERM "$FITPUB_PID" "$PROXY_PID" "$MAILPIT_PID" 2>/dev/null || true
wait "$FITPUB_PID" "$PROXY_PID" "$MAILPIT_PID" 2>/dev/null || true
kill -TERM "$PG_PID" 2>/dev/null || true
wait || true
exit "$EXIT_CODE"
